package z3java;
import java.util.HashMap;

import org.junit.Test;

import com.microsoft.z3.Context;
import com.microsoft.z3.Log;
import com.microsoft.z3.Z3Exception;

import junit.framework.TestCase;


import de.tud.exploitgen.solver.Z3Solver;

public class TestJavaExample extends TestCase{
   @Test
   public void testZ3Quantifier() throws Z3Exception{
      
      try {
         JavaExample p = new JavaExample();
         HashMap<String, String> cfg = new HashMap<String, String>();
         cfg.put("model", "true");
         Context ctx = new Context(cfg);
         Context.ToggleWarningMessages(true);
         Log.Open("test.log");
         
         p.ArrayExample1(ctx);
         System.out.println("\n------------------\n");
         p.ArrayExample3(ctx);
         
         Log.Close();
         if (Log.isOpen())
             System.out.println("Log is still open!");
      }
      catch (Exception e) {
         // TODO Auto-generated catch block
         e.printStackTrace();
      }
   }
}
